apiVersion: v1
kind: Service
metadata:
  name: os-service
  namespace: os-service
  labels:
    app: os-service
spec:
  selector:
    app: os-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
